//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MDomQuaChkSys.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MDomQuaChkSysTYPE           130
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define ID_VIEW_SOURCEDATA              155
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define ID_VIEW_LEFTIMG                 159
#define ID_VIEW_RIGHTIMG                160
#define ID_VIEW_CHART_PT                161
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDC_HEADER_OPEN                 310
#define IDC_HEADER_SIZE                 311
#define IDD_DIALOG_NEW_PRJ              312
#define IDD_DIALOG_MATCHPOINT_CHART     315
#define IDB_BITMAP1                     317
#define IDB_BITMAP_BUTTON_LARGE         317
#define IDB_BITMAP_BUTTON_SMALL         318
#define IDD_SETUP                       319
#define IDC_MFCEDITBROWSE_FOLDER_DOM    1000
#define IDC_MFCEDITBROWSE_FOLDER_REF    1001
#define IDC_LIST_IMGINFO                1002
#define IDC_CHECK_DELETE_INVALID_IMG    1003
#define IDC_CHECK2                      1004
#define IDC_CHECK_ADD_TIF               1004
#define IDC_CHECK3                      1005
#define IDC_CHECK_ADD_PIX               1005
#define IDC_STATIC_FOLDER_DOM           1006
#define IDC_STATIC_FOLDER_REF           1007
#define IDC_CHECK1                      1008
#define IDC_CHECK_ADD_IMG               1008
#define IDC_MFCEDITBROWSE_PATH_PRJ      1009
#define IDC_STATIC_PATH_PRJ             1010
#define IDC_EDIT_NUM_DOM                1011
#define IDC_EDIT2                       1012
#define IDC_EDIT_NUM_REF                1012
#define IDC_STATIC_NUM_DOM              1013
#define IDC_STATIC_NUM_REF              1014
#define ID_ITEM_IMGTREE                 1015
#define IDC_STATIC_LOOKINGFORFILES      1015
#define IDC_DATA_CHART                  1016
#define IDC_LIST_MODEL                  1017
#define IDC_LIST_POINT                  1018
#define IDC_EDIT_INFO                   1019
#define IDC_LOOKINGFORBYSTRING          1020
#define IDC_DELETEFILES                 1021
#define IDC_LOOKINGFOR                  1022
#define IDC_THREOD_PIX                  1023
#define IDC_THREOD_CIR                  1024
#define IDC_THREOD_PTNUM                1025
#define IDC_THREOD_PTNUM2               1026
#define IDC_THREOD_PTNUMControl         1026
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_NEW_PRJ               32771
#define ID_BUTTON_OPEN_PRJ              32772
#define ID_BUTTON_SAVE_PRJ              32773
#define ID_BUTTON_AUTO_MATCH            32774
#define ID_BUTTON_QUALITY_CHECK         32779
#define ID_BUTTON_CHECK_TIE             32780
#define ID_BUTTON_CHECK_CTL             32781
#define ID_BUTTON_REPORT_FILL           32783
#define ID_CHECK_VIEW_MATCHPOINT        32788
#define ID_CHECK_VIEW_RESIDUALCHART     32789
#define ID_BUTTON_SAVE_REPORT           32790
#define ID_EDIT_TIE_THRESOLD            32792
#define ID_EDIT_GCP_THRESOLD            32793
#define ID_CHECK_CQ_IMG                 32794
#define ID_CHECK_TIE_IMG                32795
#define ID_CHECK_GCP_IMG                32796
#define ID_CHECK5_VIEW_SELECT_POLYGON   32797
#define ID_BUTTON_COLOR1                32798
#define ID_BUTTON_COLOR2                32799
#define ID_BUTTON_COLOR3                32800
#define ID_BUTTON_COLOR4                32801
#define ID_CHECK_VIEW_PROPERITYWND      32802
#define ID_CHECK_VIEW_LEFTIMGWND        32803
#define ID_CHECK_VIEW_RIGHTIMGWND       32804
#define ID_CHECK_VIEW_SOURCEDATAWND     32806
#define ID_CHECK_VIEW_MODELWND          32807
#define ID_CHECK_SAVE_IMGLIST           32808
#define ID_SETUP                        32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        320
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
